// Default gem catalog for Mist Hunter Gem Helper.
// Source: community gem database (mistfalldb.com), scraped 2026-08-08, shortly after
// this game's 2026-07-29 launch. The source site itself warns that exact names/values
// may still change post-launch -- treat this as a strong starting point, not gospel.
// Use the "Gem Catalog" panel in the app to add, edit, or remove gems so your local
// copy always matches what you see in-game.
//
// Each entry: [gem name, gem type, [affix, affix2?]]
//
// There are only 4 sockets (one per colour). The source DB names gems after the
// mineral, and a socket's two tiers can carry different mineral names -- so the
// mineral is a TIER label, not a separate socket colour:
//
//   red     Lv1 "Onyx" or "Agate"                     Lv2 "Agate"
//   purple  Lv1 "Amethyst"                            Lv2 "Purple Rhomb Gem" or
//                                                         "Purple Rhombus Stone"
//   blue    Lv1 "Moonstone"                           Lv2 "Moonstone"
//   green   Lv1 "Peridot"                             Lv2 "Peridot"
//
// The purple Lv2 name splits ~32/32 between the two wordings (plus 2 entries
// reading "Purple Rhomb Stone"); they are NOT duplicates -- all 66 carry
// distinct affix pairs, so the source simply translated one item two ways.
//
// Aliasing the tier names onto the 4 real sockets makes the catalog come out
// mathematically exact: each colour has 12 affixes, one single-affix gem per
// affix (12) plus every possible pair of them, C(12,2) = 66 dual-affix gems.
// 4 x (12 + 66) = all 312 entries -- no orphans, no duplicates, nothing missing.
// Gem *names* keep their original mineral so they still match the in-game item.
const DEFAULT_GEM_TYPES = ["Agate", "Amethyst", "Moonstone", "Peridot"];

const GEM_TYPE_ALIASES = { "Onyx": "Agate", "Purple Rhomb": "Amethyst" };

const DEFAULT_GEMS = [
// --- Peridot / Moonstone / Agate / Purple Rhomb / Onyx / Amethyst, alphabetical (source page 1) ---
["Aegis Creation Moonstone", "Moonstone", ["Spirit Shield", "Creation"]],
["Aegis Curseward Moonstone", "Moonstone", ["Spirit Shield", "Curse"]],
["Aegis Fervor Moonstone", "Moonstone", ["Spirit Shield", "Fervor"]],
["Aegis Flawless Moonstone", "Moonstone", ["Spirit Shield", "Seamless"]],
["Aegis Fury Moonstone", "Moonstone", ["Spirit Shield", "Wrath"]],
["Aegis Haste Moonstone", "Moonstone", ["Spirit Shield", "Swift"]],
["Aegis: Ironhelm Agate", "Agate", ["Aegis", "Iron Helmet"]],
["Aegis: Stalwart Agate", "Agate", ["Aegis", "Stoic"]],
["Aegis: Steelwall Agate", "Agate", ["Aegis", "Bulwark"]],
["Aegis: Tenacious Agate", "Agate", ["Aegis", "Tenacious"]],
["Agile Peridot", "Peridot", ["Elusive"]],
["Agility Blessing Peridot", "Peridot", ["Elusive", "Blessing"]],
["Agility Dexterity Peridot", "Peridot", ["Elusive", "Deft"]],
["Agility Fortune Peridot", "Peridot", ["Elusive", "Wealth"]],
["Allied Burst Moonstone", "Moonstone", ["Brotherhood", "Burst"]],
["Allied Unyielding Moonstone", "Moonstone", ["Brotherhood", "Unyielding"]],
["Artifice Moonstone", "Moonstone", ["Creation"]],
["Battle Spirit: Battle Will Purple Rhomb Gem", "Purple Rhomb", ["Valor", "Fervor"]],
["Battle Spirit: Curse Resist Purple Rhomb Gem", "Purple Rhomb", ["Valor", "Curse"]],
["Battle Spirit: Fervor Purple Rhomb Gem", "Purple Rhomb", ["Valor", "Fervid"]],
["Battle Spirit: Pierce Purple Rhomb Gem", "Purple Rhomb", ["Valor", "Sky Piercer"]],
["Battle Spirit: Pursuit Purple Rhomb Gem", "Purple Rhomb", ["Valor", "Seeker"]],
["Battle Spirit: Rage Purple Rhomb Gem", "Purple Rhomb", ["Valor", "Wrath"]],
["Battle Spirit: Ranged Purple Rhomb Gem", "Purple Rhomb", ["Valor", "Ranged"]],
["Battle Spirit: Vitality Purple Rhomb Gem", "Purple Rhomb", ["Valor", "Vitality"]],
["Battlebond · Fighting Spirit Agate", "Agate", ["Brotherhood", "Valor"]],
["Battlewill·Fervor Agate", "Agate", ["Valor", "Fervid"]],
["Battlewill·Focus Agate", "Agate", ["Valor", "Focused"]],
["Battlewill·Skysunder Agate", "Agate", ["Valor", "Sky Piercer"]],
["Blast Moonstone", "Moonstone", ["Burst"]],
["Blessed Peridot", "Peridot", ["Blessing"]],
["Blessing Fortune Peridot", "Peridot", ["Blessing", "Wealth"]],
["Brawl · Focus Agate", "Agate", ["Strife", "Focused"]],
["Brawling Peridot", "Peridot", ["Strife"]],
["Brotherhood Onyx", "Onyx", ["Brotherhood"]],
["Brotherhood·Fervor Agate", "Agate", ["Brotherhood", "Fervid"]],
["Brotherhood·Focus Agate", "Agate", ["Brotherhood", "Focused"]],
["Brotherhood·Skysunder Agate", "Agate", ["Brotherhood", "Sky Piercer"]],
["Brutal Alacrity Peridot", "Peridot", ["Smiting", "Elusive"]],
["Brutal Blessed Peridot", "Peridot", ["Smiting", "Blessing"]],
["Brutal Cunning Peridot", "Peridot", ["Smiting", "Eloquence"]],
["Brutal Flawless Peridot", "Peridot", ["Smiting", "Seamless"]],
["Brutal Fortune Peridot", "Peridot", ["Smiting", "Wealth"]],
["Brutal Sleight Peridot", "Peridot", ["Smiting", "Deft"]],
["Brutal Vitality Peridot", "Peridot", ["Smiting", "Vitality"]],
["Bulwark·Brotherhood Agate", "Agate", ["Bulwark", "Brotherhood"]],
["Bulwark·Endurance Agate", "Agate", ["Bulwark", "Stoic"]],
["Bulwark·Iron Helm Agate", "Agate", ["Bulwark", "Iron Helmet"]],
["Burst Haste Moonstone", "Moonstone", ["Burst", "Swift"]],
["Burst Seamless Moonstone", "Moonstone", ["Burst", "Seamless"]],
["Bursting - Conjuring Moonstone", "Moonstone", ["Burst", "Creation"]],
["Bursting - Cursing Moonstone", "Moonstone", ["Burst", "Curse"]],
["Camaraderie · Brawl Agate", "Agate", ["Brotherhood", "Strife"]],
["Camaraderie · Ranged Ward Agate", "Agate", ["Brotherhood", "Distant Ward"]],
["Carnage Onyx", "Onyx", ["Strife"]],
["Crush · Melee Peridot", "Peridot", ["Smiting", "Strife"]],
["Crushing Peridot", "Peridot", ["Smiting"]],
["Cunning Alacrity Peridot", "Peridot", ["Eloquence", "Elusive"]],
["Cunning Blessed Peridot", "Peridot", ["Eloquence", "Blessing"]],
["Cunning Flawless Peridot", "Peridot", ["Eloquence", "Seamless"]],
["Cunning Fortune Peridot", "Peridot", ["Eloquence", "Wealth"]],
["Cunning Sleight Peridot", "Peridot", ["Eloquence", "Deft"]],
["Cunning Vitality Peridot", "Peridot", ["Eloquence", "Vitality"]],
["Curseward · Craft Moonstone", "Moonstone", ["Curse", "Creation"]],
["Curseward Amethyst", "Amethyst", ["Curse"]],
["Curseward Moonstone", "Moonstone", ["Curse"]],
["Deft Peridot", "Peridot", ["Deft"]],
["Dexterity Blessing Peridot", "Peridot", ["Deft", "Blessing"]],
["Dexterity Fortune Peridot", "Peridot", ["Deft", "Wealth"]],
["Farguard Peridot", "Peridot", ["Distant Ward"]],
["Farstrike Peridot", "Peridot", ["Ranged"]],
["Fervor · Brawl Agate", "Agate", ["Fervid", "Strife"]],
["Fervor · Craft Moonstone", "Moonstone", ["Fervor", "Creation"]],
["Fervor · Curseward Moonstone", "Moonstone", ["Fervor", "Curse"]],
["Fervor · Haste Moonstone", "Moonstone", ["Fervor", "Swift"]],
["Fervor · Seamless Moonstone", "Moonstone", ["Fervor", "Seamless"]],
["Fervor Amethyst", "Amethyst", ["Fervid"]],
["Fervor Onyx", "Onyx", ["Fervid"]],
["Fervor·Focus Agate", "Agate", ["Fervid", "Focused"]],
["Fierce Battle: Blessed Peridot", "Peridot", ["Strife", "Blessing"]],
["Fierce Battle: Deft Peridot", "Peridot", ["Strife", "Deft"]],
["Fierce Battle: Nimble Peridot", "Peridot", ["Strife", "Elusive"]],
["Fierce Battle: Wealth Peridot", "Peridot", ["Strife", "Wealth"]],
["Fighting Spirit · Brawl Agate", "Agate", ["Valor", "Strife"]],
["Flawless Agility Peridot", "Peridot", ["Seamless", "Elusive"]],
["Flawless Blessing Peridot", "Peridot", ["Seamless", "Blessing"]],
["Flawless Dexterity Peridot", "Peridot", ["Seamless", "Deft"]],
["Flawless Fortune Peridot", "Peridot", ["Seamless", "Wealth"]],
["Flawless Peridot", "Peridot", ["Seamless"]],
["Flawless Vitality Peridot", "Peridot", ["Seamless", "Vitality"]],
["Focus Onyx", "Onyx", ["Focused"]],
["Fortitude · Battlebond Agate", "Agate", ["Stoic", "Brotherhood"]],
["Fortitude · Brawl Agate", "Agate", ["Stoic", "Strife"]],
["Fortitude · Fervor Agate", "Agate", ["Stoic", "Fervid"]],
["Fortitude · Fighting Spirit Agate", "Agate", ["Stoic", "Valor"]],
["Fortitude · Fighting Spirit Purple Rhomb Stone", "Purple Rhomb", ["Stoic", "Valor"]],
["Fortitude · Focus Agate", "Agate", ["Stoic", "Focused"]],
["Fortitude · Rage Purple Rhomb Stone", "Purple Rhomb", ["Stoic", "Wrath"]],
["Fortitude · Ranged Ward Agate", "Agate", ["Stoic", "Distant Ward"]],
["Fortitude · Skycleave Agate", "Agate", ["Stoic", "Sky Piercer"]],

// --- source page 2 ---
["Fortitude Amethyst", "Amethyst", ["Stoic"]],
["Fortitude Onyx", "Onyx", ["Stoic"]],
["Fortitude: Battle Will Purple Rhomb Gem", "Purple Rhomb", ["Stoic", "Fervor"]],
["Fortitude: Curse Resist Purple Rhomb Gem", "Purple Rhomb", ["Stoic", "Curse"]],
["Fortitude: Fervor Purple Rhomb Gem", "Purple Rhomb", ["Stoic", "Fervid"]],
["Fortitude: Pierce Purple Rhomb Gem", "Purple Rhomb", ["Stoic", "Sky Piercer"]],
["Fortitude: Pursuit Purple Rhomb Gem", "Purple Rhomb", ["Stoic", "Seeker"]],
["Fortitude: Ranged Purple Rhomb Gem", "Purple Rhomb", ["Stoic", "Ranged"]],
["Fortitude: Vitality Purple Rhomb Gem", "Purple Rhomb", ["Stoic", "Vitality"]],
["Fortitude·Brotherhood Agate", "Agate", ["Tenacious", "Brotherhood"]],
["Fortitude·Bulwark Agate", "Agate", ["Tenacious", "Bulwark"]],
["Fortitude·Endurance Agate", "Agate", ["Tenacious", "Stoic"]],
["Fortitude·Focus Agate", "Agate", ["Tenacious", "Focused"]],
["Fortitude·Hotblood Agate", "Agate", ["Tenacious", "Fervid"]],
["Fortitude·Iron Helm Agate", "Agate", ["Tenacious", "Iron Helmet"]],
["Fortitude·Resilience Purple Rhomb Gem", "Purple Rhomb", ["Stoic", "Resilience"]],
["Fortitude·Skysunder Agate", "Agate", ["Tenacious", "Sky Piercer"]],
["Fortitude·Unyielding Purple Rhomb Gem", "Purple Rhomb", ["Stoic", "Unyielding"]],
["Fortitude·Zeal Agate", "Agate", ["Tenacious", "Valor"]],
["Fortune Peridot", "Peridot", ["Wealth"]],
["Fury Fervor Moonstone", "Moonstone", ["Wrath", "Fervor"]],
["Fury Flawless Moonstone", "Moonstone", ["Wrath", "Seamless"]],
["Guardian Moonstone", "Moonstone", ["Aegis"]],
["Haste · Craft Moonstone", "Moonstone", ["Swift", "Creation"]],
["Haste · Curseward Moonstone", "Moonstone", ["Swift", "Curse"]],
["Haste Moonstone", "Moonstone", ["Swift"]],
["Hotblood·Battle Zeal Purple Rhombus Stone", "Purple Rhomb", ["Fervid", "Fervor"]],
["Hotblood·Curseward Purple Rhomb Gem", "Purple Rhomb", ["Fervid", "Curse"]],
["Hotblood·Pursuit Purple Rhombus Stone", "Purple Rhomb", ["Fervid", "Seeker"]],
["Hotblood·Ranged Purple Rhombus Stone", "Purple Rhomb", ["Fervid", "Ranged"]],
["Hotblood·Vigor Purple Rhombus Stone", "Purple Rhomb", ["Fervid", "Vitality"]],
["Impenetrable Moonstone", "Moonstone", ["Seamless"]],
["Iron Helm · Battlebond Agate", "Agate", ["Iron Helmet", "Brotherhood"]],
["Iron Helm · Brawl Agate", "Agate", ["Iron Helmet", "Strife"]],
["Iron Helm · Fervor Agate", "Agate", ["Iron Helmet", "Fervid"]],
["Iron Helm · Fighting Spirit Agate", "Agate", ["Iron Helmet", "Valor"]],
["Iron Helm · Focus Agate", "Agate", ["Iron Helmet", "Focused"]],
["Iron Helm · Fortitude Agate", "Agate", ["Iron Helmet", "Stoic"]],
["Iron Helm · Skycleave Agate", "Agate", ["Iron Helmet", "Sky Piercer"]],
["Iron Helm Agate", "Agate", ["Iron Helmet"]],
["Ironhelm·Rangeward Agate", "Agate", ["Iron Helmet", "Distant Ward"]],
["Light·Aegis Moonstone", "Moonstone", ["Ethereal", "Spirit Shield"]],
["Light·Cleansing Moonstone", "Moonstone", ["Ethereal", "Curse"]],
["Light·Fervor Moonstone", "Moonstone", ["Ethereal", "Fervor"]],
["Light·Flawless Moonstone", "Moonstone", ["Ethereal", "Seamless"]],
["Light·Haste Moonstone", "Moonstone", ["Ethereal", "Swift"]],
["Light·Unity Moonstone", "Moonstone", ["Ethereal", "Brotherhood"]],
["Light·Wrath Moonstone", "Moonstone", ["Ethereal", "Wrath"]],
["Lightfoot Moonstone", "Moonstone", ["Ethereal"]],
["Lightweight Burst Moonstone", "Moonstone", ["Ethereal", "Burst"]],
["Lightweight Creation Moonstone", "Moonstone", ["Ethereal", "Creation"]],
["Melee · Bulwark Peridot", "Peridot", ["Strife", "Seamless"]],
["Melee · Persuasion Peridot", "Peridot", ["Strife", "Eloquence"]],
["Melee · Vitality Peridot", "Peridot", ["Strife", "Vitality"]],
["Nimble · Unyielding Moonstone", "Moonstone", ["Ethereal", "Unyielding"]],
["Persuasive Peridot", "Peridot", ["Eloquence"]],
["Pierce · Brawl Agate", "Agate", ["Sky Piercer", "Strife"]],
["Pursuit Amethyst", "Amethyst", ["Seeker"]],
["Pursuit·Curseward Purple Rhomb Gem", "Purple Rhomb", ["Seeker", "Curse"]],
["Pursuit·Ranged Purple Rhomb Gem", "Purple Rhomb", ["Seeker", "Ranged"]],
["Pursuit·Vitality Purple Rhomb Gem", "Purple Rhomb", ["Seeker", "Vitality"]],
["Pursuit·Zeal Purple Rhomb Gem", "Purple Rhomb", ["Seeker", "Fervor"]],
["Rage · Craft Moonstone", "Moonstone", ["Wrath", "Creation"]],
["Rage · Curseward Moonstone", "Moonstone", ["Wrath", "Curse"]],
["Rage · Haste Moonstone", "Moonstone", ["Wrath", "Swift"]],
["Rage: Pierce Purple Rhomb Gem", "Purple Rhomb", ["Wrath", "Sky Piercer"]],
["Ranged - Agile Peridot", "Peridot", ["Ranged", "Elusive"]],
["Ranged - Flawless Peridot", "Peridot", ["Ranged", "Seamless"]],
["Ranged - Smiting Peridot", "Peridot", ["Ranged", "Smiting"]],
["Ranged - Vigorous Peridot", "Peridot", ["Ranged", "Vitality"]],
["Ranged - Wily Peridot", "Peridot", ["Ranged", "Eloquence"]],
["Ranged · Melee Peridot", "Peridot", ["Ranged", "Strife"]],
["Ranged Blessed Peridot", "Peridot", ["Ranged", "Blessing"]],
["Ranged Fortune Peridot", "Peridot", ["Ranged", "Wealth"]],
["Ranged Power Amethyst", "Amethyst", ["Ranged"]],
["Ranged Sleight Peridot", "Peridot", ["Ranged", "Deft"]],
["Ranged Ward · Agility Peridot", "Peridot", ["Distant Ward", "Elusive"]],
["Ranged Ward · Blessing Peridot", "Peridot", ["Distant Ward", "Blessing"]],
["Ranged Ward · Brawl Agate", "Agate", ["Distant Ward", "Strife"]],
["Ranged Ward · Bulwark Peridot", "Peridot", ["Distant Ward", "Seamless"]],
["Ranged Ward · Crush Peridot", "Peridot", ["Distant Ward", "Smiting"]],
["Ranged Ward · Dexterity Peridot", "Peridot", ["Distant Ward", "Deft"]],
["Ranged Ward · Fervor Agate", "Agate", ["Distant Ward", "Fervid"]],
["Ranged Ward · Fighting Spirit Agate", "Agate", ["Distant Ward", "Valor"]],
["Ranged Ward · Focus Agate", "Agate", ["Distant Ward", "Focused"]],
["Ranged Ward · Fortune Peridot", "Peridot", ["Distant Ward", "Wealth"]],
["Ranged Ward · Melee Peridot", "Peridot", ["Distant Ward", "Strife"]],
["Ranged Ward · Persuasion Peridot", "Peridot", ["Distant Ward", "Eloquence"]],
["Ranged Ward · Pierce Agate", "Agate", ["Distant Ward", "Sky Piercer"]],
["Ranged Ward · Ranged Peridot", "Peridot", ["Distant Ward", "Ranged"]],
["Ranged Ward · Vitality Peridot", "Peridot", ["Distant Ward", "Vitality"]],
["Ranged Ward Onyx", "Onyx", ["Distant Ward"]],
["Ranged·Curseward Purple Rhomb Gem", "Purple Rhomb", ["Ranged", "Curse"]],
["Ranged·Vitality Purple Rhomb Gem", "Purple Rhomb", ["Ranged", "Vitality"]],
["Ranged·Zeal Purple Rhomb Gem", "Purple Rhomb", ["Ranged", "Fervor"]],
["Resilience Amethyst", "Amethyst", ["Resilience"]],
["Resolve Amethyst", "Amethyst", ["Valor"]],
["Resolve Onyx", "Onyx", ["Valor"]],
["Seamless · Craft Moonstone", "Moonstone", ["Seamless", "Creation"]],
["Seamless · Curseward Moonstone", "Moonstone", ["Seamless", "Curse"]],

// --- source page 3 ---
["Seamless · Haste Moonstone", "Moonstone", ["Seamless", "Swift"]],
["Skycleave·Battle Zeal Purple Rhombus Stone", "Purple Rhomb", ["Sky Piercer", "Fervor"]],
["Skycleave·Cursebreak Purple Rhombus Stone", "Purple Rhomb", ["Sky Piercer", "Curse"]],
["Skycleave·Hotblood Purple Rhombus Stone", "Purple Rhomb", ["Sky Piercer", "Fervid"]],
["Skycleave·Pursuit Purple Rhombus Stone", "Purple Rhomb", ["Sky Piercer", "Seeker"]],
["Skycleave·Ranged Purple Rhombus Stone", "Purple Rhomb", ["Sky Piercer", "Ranged"]],
["Skycleave·Vigor Purple Rhombus Stone", "Purple Rhomb", ["Sky Piercer", "Vitality"]],
["Skyshatter Amethyst", "Amethyst", ["Sky Piercer"]],
["Skyshatter Onyx", "Onyx", ["Sky Piercer"]],
["Skysunder·Fervor Agate", "Agate", ["Sky Piercer", "Fervid"]],
["Skysunder·Focus Agate", "Agate", ["Sky Piercer", "Focused"]],
["Spellshield Burst Moonstone", "Moonstone", ["Spirit Shield", "Burst"]],
["Spellshield Moonstone", "Moonstone", ["Spirit Shield"]],
["Spellshield Unyielding Moonstone", "Moonstone", ["Spirit Shield", "Unyielding"]],
["Steel Bulwark · Fervor Agate", "Agate", ["Bulwark", "Fervid"]],
["Steel Bulwark · Fighting Spirit Agate", "Agate", ["Bulwark", "Valor"]],
["Steel Bulwark · Focus Agate", "Agate", ["Bulwark", "Focused"]],
["Steel Bulwark · Skycleave Agate", "Agate", ["Bulwark", "Sky Piercer"]],
["Steel Bulwark Agate", "Agate", ["Bulwark"]],
["Steelwall·Brawl Agate", "Agate", ["Bulwark", "Strife"]],
["Steelwall·Rangeward Agate", "Agate", ["Bulwark", "Distant Ward"]],
["Tenacious - Agile Peridot", "Peridot", ["Tenacious", "Elusive"]],
["Tenacious - Blessed Peridot", "Peridot", ["Tenacious", "Blessing"]],
["Tenacious - Dexterous Peridot", "Peridot", ["Tenacious", "Deft"]],
["Tenacious - Flawless Peridot", "Peridot", ["Tenacious", "Seamless"]],
["Tenacious - Fortunate Peridot", "Peridot", ["Tenacious", "Wealth"]],
["Tenacious - Ranged Peridot", "Peridot", ["Tenacious", "Ranged"]],
["Tenacious - Smiting Peridot", "Peridot", ["Tenacious", "Smiting"]],
["Tenacious - Vigorous Peridot", "Peridot", ["Tenacious", "Vitality"]],
["Tenacious - Wily Peridot", "Peridot", ["Tenacious", "Eloquence"]],
["Tenacious Peridot", "Peridot", ["Tenacious"]],
["Tenacity · Armor Pierce Purple Rhombus Stone", "Purple Rhomb", ["Resilience", "Sky Piercer"]],
["Tenacity · Battle Will Purple Rhombus Stone", "Purple Rhomb", ["Resilience", "Fervor"]],
["Tenacity · Curse Resistance Purple Rhombus Stone", "Purple Rhomb", ["Resilience", "Curse"]],
["Tenacity · Fervor Purple Rhombus Stone", "Purple Rhomb", ["Resilience", "Fervid"]],
["Tenacity · Fighting Spirit Purple Rhombus Stone", "Purple Rhomb", ["Resilience", "Valor"]],
["Tenacity · Fury Purple Rhombus Stone", "Purple Rhomb", ["Resilience", "Wrath"]],
["Tenacity · Melee Peridot", "Peridot", ["Tenacious", "Strife"]],
["Tenacity · Pursuit Purple Rhombus Stone", "Purple Rhomb", ["Resilience", "Seeker"]],
["Tenacity · Ranged Attack Purple Rhombus Stone", "Purple Rhomb", ["Resilience", "Ranged"]],
["Tenacity · Vitality Purple Rhombus Stone", "Purple Rhomb", ["Resilience", "Vitality"]],
["Tenacity Agate", "Agate", ["Tenacious"]],
["Tenacity Ranged Ward Peridot", "Peridot", ["Tenacious", "Distant Ward"]],
["Tenacity·Brawl Agate", "Agate", ["Tenacious", "Strife"]],
["Tenacity·Rangeward Agate", "Agate", ["Tenacious", "Distant Ward"]],
["Unity Aegis Moonstone", "Moonstone", ["Brotherhood", "Spirit Shield"]],
["Unity Creation Moonstone", "Moonstone", ["Brotherhood", "Creation"]],
["Unity Curseward Moonstone", "Moonstone", ["Brotherhood", "Curse"]],
["Unity Fervor Moonstone", "Moonstone", ["Brotherhood", "Fervor"]],
["Unity Flawless Moonstone", "Moonstone", ["Brotherhood", "Seamless"]],
["Unity Fury Moonstone", "Moonstone", ["Brotherhood", "Wrath"]],
["Unity Haste Moonstone", "Moonstone", ["Brotherhood", "Swift"]],
["Unity Moonstone", "Moonstone", ["Brotherhood"]],
["Unyielding · Armor Pierce Purple Rhombus Stone", "Purple Rhomb", ["Unyielding", "Sky Piercer"]],
["Unyielding · Battle Will Purple Rhombus Stone", "Purple Rhomb", ["Unyielding", "Fervor"]],
["Unyielding · Curse Resistance Purple Rhombus Stone", "Purple Rhomb", ["Unyielding", "Curse"]],
["Unyielding · Fervor Purple Rhombus Stone", "Purple Rhomb", ["Unyielding", "Fervid"]],
["Unyielding · Pursuit Purple Rhombus Stone", "Purple Rhomb", ["Unyielding", "Seeker"]],
["Unyielding · Ranged Attack Purple Rhombus Stone", "Purple Rhomb", ["Unyielding", "Ranged"]],
["Unyielding · Vitality Purple Rhombus Stone", "Purple Rhomb", ["Unyielding", "Vitality"]],
["Unyielding Amethyst", "Amethyst", ["Unyielding"]],
["Unyielding Burst Moonstone", "Moonstone", ["Unyielding", "Burst"]],
["Unyielding Creation Moonstone", "Moonstone", ["Unyielding", "Creation"]],
["Unyielding Curseward Moonstone", "Moonstone", ["Unyielding", "Curse"]],
["Unyielding Haste Moonstone", "Moonstone", ["Unyielding", "Swift"]],
["Unyielding Moonstone", "Moonstone", ["Unyielding"]],
["Unyielding Seamless Moonstone", "Moonstone", ["Unyielding", "Seamless"]],
["Unyielding Wrath Moonstone", "Moonstone", ["Unyielding", "Wrath"]],
["Unyielding Zeal Moonstone", "Moonstone", ["Unyielding", "Fervor"]],
["Unyielding·Rage Purple Rhomb Gem", "Purple Rhomb", ["Unyielding", "Wrath"]],
["Unyielding·Resilience Purple Rhomb Gem", "Purple Rhomb", ["Unyielding", "Resilience"]],
["Unyielding·Resolve Purple Rhomb Gem", "Purple Rhomb", ["Unyielding", "Valor"]],
["Vital Peridot", "Peridot", ["Vitality"]],
["Vitality Agility Peridot", "Peridot", ["Vitality", "Elusive"]],
["Vitality Amethyst", "Amethyst", ["Vitality"]],
["Vitality Blessing Peridot", "Peridot", ["Vitality", "Blessing"]],
["Vitality Dexterity Peridot", "Peridot", ["Vitality", "Deft"]],
["Vitality Fortune Peridot", "Peridot", ["Vitality", "Wealth"]],
["Vitality·Curseward Purple Rhomb Gem", "Purple Rhomb", ["Vitality", "Curse"]],
["Ward·Aegis Moonstone", "Moonstone", ["Aegis", "Spirit Shield"]],
["Ward·Brawl Agate", "Agate", ["Aegis", "Strife"]],
["Ward·Cleansing Moonstone", "Moonstone", ["Aegis", "Curse"]],
["Ward·Craft Moonstone", "Moonstone", ["Aegis", "Creation"]],
["Ward·Fervor Moonstone", "Moonstone", ["Aegis", "Fervor"]],
["Ward·Flawless Moonstone", "Moonstone", ["Aegis", "Seamless"]],
["Ward·Haste Moonstone", "Moonstone", ["Aegis", "Swift"]],
["Ward·Light Moonstone", "Moonstone", ["Aegis", "Ethereal"]],
["Ward·Rangeward Agate", "Agate", ["Aegis", "Distant Ward"]],
["Ward·Unity Moonstone", "Moonstone", ["Aegis", "Brotherhood"]],
["Ward·Wrath Moonstone", "Moonstone", ["Aegis", "Wrath"]],
["Warding · Burst Moonstone", "Moonstone", ["Aegis", "Burst"]],
["Warding · Unyielding Moonstone", "Moonstone", ["Aegis", "Unyielding"]],

// --- source page 4 ---
["Warding Agate", "Agate", ["Aegis"]],
["Warding·Brotherhood Agate", "Agate", ["Aegis", "Brotherhood"]],
["Warding·Focus Agate", "Agate", ["Aegis", "Focused"]],
["Warding·Hotblood Agate", "Agate", ["Aegis", "Fervid"]],
["Warding·Skysunder Agate", "Agate", ["Aegis", "Sky Piercer"]],
["Warding·Zeal Agate", "Agate", ["Aegis", "Valor"]],
["Warspirit Amethyst", "Amethyst", ["Fervor"]],
["Warspirit Moonstone", "Moonstone", ["Fervor"]],
["Wrath Amethyst", "Amethyst", ["Wrath"]],
["Wrath Burst Moonstone", "Moonstone", ["Wrath", "Burst"]],
["Wrath Moonstone", "Moonstone", ["Wrath"]],
["Wrath·Battle Zeal Purple Rhombus Stone", "Purple Rhomb", ["Wrath", "Fervor"]],
["Wrath·Cursebreak Purple Rhombus Stone", "Purple Rhomb", ["Wrath", "Curse"]],
["Wrath·Hotblood Purple Rhombus Stone", "Purple Rhomb", ["Wrath", "Fervid"]],
["Wrath·Pursuit Purple Rhombus Stone", "Purple Rhomb", ["Wrath", "Seeker"]],
["Wrath·Ranged Purple Rhombus Stone", "Purple Rhomb", ["Wrath", "Ranged"]],
["Wrath·Vigor Purple Rhombus Stone", "Purple Rhomb", ["Wrath", "Vitality"]],
["Zeal Burst Moonstone", "Moonstone", ["Fervor", "Burst"]],
["Zeal·Curseward Purple Rhomb Gem", "Purple Rhomb", ["Fervor", "Curse"]],
["Zeal·Vitality Purple Rhomb Gem", "Purple Rhomb", ["Fervor", "Vitality"]],
].map(([name, type, affixes], i) => ({
  id: "default-" + i,
  name,
  type: GEM_TYPE_ALIASES[type] || type, // fold mineral tier names onto the 4 real sockets
  sourceType: type,                     // what the source DB called it, kept for reference
  affixes,
  custom: false,
}));

const DEFAULT_AFFIXES = Array.from(
  new Set(DEFAULT_GEMS.flatMap(g => g.affixes))
).sort();

// Each affix's own in-game level cap -- most top out at 7, a chunk of them cap
// lower at 5. Stacking more gems than this on one affix does nothing, so the
// solver treats this as a hard ceiling regardless of what min/max you set.
// Source: per-level tooltip breakdowns on the same community affix guide.
const AFFIX_MAX_LEVEL = {
  "Valor": 7, "Eloquence": 7, "Stoic": 7, "Ranged": 7,
  "Unyielding": 7, "Seamless": 7, "Resilience": 5, "Aegis": 7, "Seeker": 5,
  "Sky Piercer": 7, "Fervor": 7, "Strife": 7,
  "Fervid": 7, "Vitality": 5, "Elusive": 5, "Wrath": 7,
  "Tenacious": 7, "Iron Helmet": 5, "Distant Ward": 7,
  "Curse": 5, "Focused": 7, "Blessing": 5, "Bulwark": 5, "Burst": 5,
  "Creation": 7, "Wealth": 5, "Deft": 5, "Swift": 5,
  "Spirit Shield": 7, "Brotherhood": 7, "Ethereal": 5, "Smiting": 5,
};

// Visual shorthand for each gem type: colour + cut, matched to an in-game
// screenshot of the socketing UI (Agate=red emerald-cut, Amethyst=purple
// triangle, Moonstone=cyan square, Peridot=green octagon). "Universal"
// (the any-colour socket found on necklaces) gets a plain neutral circle.
const GEM_TYPE_STYLE = {
  Agate: { color: "#E11D48", shape: "emerald" },
  Amethyst: { color: "#9333EA", shape: "triangle" },
  Moonstone: { color: "#22D3EE", shape: "square" },
  Peridot: { color: "#22C55E", shape: "octagon" },
  Universal: { color: "#94A3B8", shape: "circle" },
};

const GEM_SHAPE_PATHS = {
  // regular octagon: equal-length sides all the way round
  octagon: "M8.7,4 L15.3,4 L20,8.7 L20,15.3 L15.3,20 L8.7,20 L4,15.3 L4,8.7 Z",
  // clearly narrower than tall, unlike the earlier near-square cut
  emerald: "M9.5,4 L14.5,4 L17,6.5 L17,17.5 L14.5,20 L9.5,20 L7,17.5 L7,6.5 Z",
  triangle: "M12,4 L20,19 L4,19 Z",
};
